


spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: 오라클 url
    username: 유저이름
    password: 비밀번호
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
  servlet: # 파일 업로드시 첨부파일 크기 지정
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
  web:
      resources:
                static-locations: classpath:/upload/
      image:
        image-dir: src/main/resources
      devtools:
        livereload:
          enabled: true
        remote:
          restart:
            enabled: true

  image:
    image-dir: src/main/resources

# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.ohgiraffers.intranet,
                        com.ohgiraffers.intranet.notice.model.dto,
                        com.ohgiraffers.intranet.empManage.model.dto,
                        com.ohgiraffers.intranet.member.model.dto,
                        com.ohgiraffers.intranet.deptNotice.model.dto
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
