


spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle.coffit.site:1521:xe
    username: C##INTRANET
    password: INTRANET


# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
