


spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@oracle.coffit.site:1521:xe
    username: C##INTRANET
    password: INTRANET
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.ohgiraffers.intranet
  configuration:
    map-underscore-to-camel-case: true